### ISSUE TITLE
Add pages & posts for SAB1562

### ISSUE THREAD

**Issue by rmidura** [EMmobility/EmDigIt#1]

**Comment by rmidura** [comment]
Hi Sean, would it be possible to accomplish this by next Friday?

**Comment by slee908** [comment]
Hi Rachel,


Sorry for the delay! After finishing up with my last assignment from Katie, I started on SAA1550 to ease into the assignments you gave me, and I will start/finish SAB1562 next week!


For entries that do not have a indicated number of posts, am I supposed to count the number of posts manually or put NA in that column? On SAA1550, for entries where there was no indicated total number of posts I left a question mark.


Sincerely,

Sean

________________________________

**Comment by rmidura** [comment]
Hi Sean! Yes, I see now the page has been cut off in those cases- that will work fine, thank you. You can always ping me on Slack if you come across a situation you are unsure about while working.

**Comment by slee908** [comment]
I finished!

**Comment by rmidura** [comment]
Excellent, thanks Sean! I'm going to go ahead and assign a few more, let's plan to check in next week. When will you be around CESTA?
