### ISSUE TITLE
Read data schema and run sanity checks

### ISSUE THREAD

**Issue by rmidura** [EMmobility/EmDigIt#13]
Review the Data Schema and acquaint yourself with the structure of the EmDigIt database:
https://drive.google.com/open?id=1z4H_7w76Z9zTxJY4C-EpE175Gb7Hf_akjztWyDFoyOU

Use the programming language of your choice (or Sheets) to determine that the following are true:

Route_Table
All last_dates are => to first_dates
If Dup_Bw_Titles=False, then Dup_Bw_Authors=False
If duration=0, Dup_Bw_Titles and Dup_Bw_Authors=False
If international=true, interregional=true

**Comment by rmidura** [comment]
I've figured out an Edge_First_Date and Edge_Last_Date column for the Edge_Table. I've changed instead the final item to a sanity check to make sure that these dates are correct with reference to the Route_First_Date and Route_Last_Date in the Route_Table from which they originate.

**Comment by isabdr** [comment]
All sanity checks for Route_Table are done!
[Route_Table Sanity Checks.py.zip](https://github.com/EMmobility/EmDigIt/files/3122735/Route_Table.Sanity.Checks.py.zip)
