### ISSUE TITLE
Road_Table Creation

### ISSUE THREAD

**Issue by rmidura** [EMmobility/EmDigIt#14]
1. Beginning from the Route_Table, determine a list of all unique combinations of the **two first values** in the Route_Comb column (representing the origin;destination) as found in the Route_Comb column (in any directionality). Ex: 2;38;19 and 2;38 and 38;2 would represent a single unique value.

2. Create a new Road_Table, and provide preceding list as column "Road_Locations" with a column "Road_ID" consisting of sequential integers (1, 2, 3, etc.). 

3. Create a new column ("Linked_Routes") which indicates which Route_IDs can be grouped as belonging to these Road_IDs. 

See example with random numbers at "Road_Table_Ex." Note commented first row.

**Comment by rmidura** [comment]
Edited 1 for clarity

**Comment by isabdr** [comment]
I did items 1) and 2). I'll work on figuring out the Linked_Routes column now.

[Road_Table.ipynb.zip](https://github.com/EMmobility/EmDigIt/files/3136176/Road_Table.ipynb.zip)

**Comment by rmidura** [comment]
Looks great! If you are able, it would be nice to have the Road_Locations back in the input format (i.e 5;16 instead of [5,16]). However this is a quick fix in sheets, so don't bother if it will take more than 15 min or so.

**Comment by rmidura** [comment]
EDIT: Never mind, good opportunity for me to figure out some Python! I modified the code slightly to allow for variable lengths of the input (since edits may happen down the road) and added some code for exporting a version with the string-with-semicolons format.

[Road_Table_Edit.ipynb.zip](https://github.com/EMmobility/EmDigIt/files/3136457/Road_Table_Edit.ipynb.zip)

**Comment by isabdr** [comment]
Finished! Here is the Jupyter Notebook file of the code:
[Road_Table Final.ipynb.zip](https://github.com/EMmobility/EmDigIt/files/3143682/Road_Table.Final.ipynb.zip)

and here is the new Road_Table in csv:
[Road_Table.csv.zip](https://github.com/EMmobility/EmDigIt/files/3143683/Road_Table.csv.zip)

The table has 3 columns: Road_IDs, Road_Locations, and Linked_Routes

**Comment by rmidura** [comment]
Great work, Bela! Thanks for this.

I'm going to go ahead and assign the next issue, but Leo told me he will
have you doing more work on his side of things. Feel free to switch between
things as seems interesting/convenient!

All the best,
RM
